# Generated by Django 3.0.5 on 2020-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('contractor', 'Contractor')], default='customer', max_length=20),
        ),
    ]
