# Generated by Django 3.0.3 on 2020-06-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200609_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shopname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
