# Generated by Django 3.0.3 on 2020-06-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200609_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendorShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('on', 'ON'), ('off', 'OFF')], default='', max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('first_phone', models.CharField(blank=True, default='', max_length=20)),
                ('second_phone', models.CharField(blank=True, default='', max_length=20)),
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
