# Generated by Django 3.0.5 on 2020-07-10 17:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200710_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='product_placeholder.jpg', null=True, upload_to=accounts.models.get_image_filename, verbose_name='product_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='product_image', to='accounts.Images'),
        ),
    ]
