# Generated by Django 3.0.3 on 2020-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200714_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='product_image', to='accounts.Images'),
        ),
    ]
